@startuml

actor Controller

Controller -> findNearestCabinCommand: execute(HashMap<String, Object>)
activate findNearestCabinCommand
findNearestCabinCommand -> Controller: getSequenceToOrder()
deactivate findNearestCabinCommand
Controller -> Controller: moveSequence
activate Controller
Controller -> Shaft: updateSequence
deactivate Controller
Controller <-- Shaft
@enduml

