@startuml

actor Controller

Controller -> findNearestCabinCommand: execute(HashMap<String, Object>)
activate findNearestCabinCommand
findNearestCabinCommand -> Controller: addSequenceToOrder()
deactivate findNearestCabinCommand
Controller -> Controller: moveSequence

@enduml
