@startuml

entity House {
id: int
numberOfFloors: int
numberOfShafts: int
}

entity Shaft {
id: int
cabinPosition: int
doorState: varchar
engineState: varchar
houseId: int
}

House "1 houseId" o-- "N numberOfShafts" Shaft

entity OrderSequenceOfStops {
id: int
stopFloors: array
direction: varchar
}

entity ElevatorDriver {
id: int
houseId: int
}

entity SequenceOfStopsDistributor {
id: int
sequenceOfStopsId: int
elevatorDriverId: int
shaftId: int
done: boolean
}

House "1" o-- "1" ElevatorDriver

SequenceOfStopsDistributor "N" --o "1" ElevatorDriver

SequenceOfStopsDistributor "N" --o "1" OrderSequenceOfStops

Shaft "1" o-- "1" SequenceOfStopsDistributor

@enduml