spring:
  datasource:
    username: sa
    password: pwd
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master-test.yml

house:
  elevatorCountCabin: 2
  floorsCount: 16

houseThreadPool:
  openDoorTimeSleep: 0
  closeDoorTimeSleep: 0
  visitFloorTimeSleep: 0
  moveCabinTimeSleep: 0
