spring:
  datasource:
    username: sa
    password: pwd
    url: jdbc:h2:file:./db/demodb;
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

house:
  elevatorCountCabin: 2
  floorsCount: 16