@startuml

actor Passenger

Passenger -> Floor: pressUpButton()
Floor -> FloorButton: press(floorNumber)
FloorButton -> PressUpButtonCommand: execute(params)
PressUpButtonCommand -> FindNearestCabinCommand: execute(params)
FindNearestCabinCommand -> MoveCabinCommand: execute(params)
MoveCabinCommand -> StartEngineCommand: execute(params)
MoveCabinCommand -> VisitFloorCommand: execute(params)

VisitFloorCommand -> Shaft: setCabinPosition(cabinPosition)
Shaft -> ElevatorDriver: handleCabinPositionChanged(event)
activate ElevatorDriver
ElevatorDriver -> StopEngineCommand: execute(params)
ElevatorDriver -> OpenDoorCommand: execute(params)
OpenDoorCommand -> Shaft: openDoor()
deactivate ElevatorDriver
Shaft -> ElevatorDriver: handleDoorStateChanged(event)
ElevatorDriver -> CloseDoorCommand: execute(params)
CloseDoorCommand -> Shaft: closeDoor()
Shaft -> ElevatorDriver: handleDoorStateChanged(event)
ElevatorDriver -> Shaft: clearSequence()

@enduml
